root_dir: "artifacts"

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  images_path: "artifacts/data_ingestion/images"
  labels_path: "artifacts/data_ingestion/labels"
  dataset_config_path: "artifacts/data_ingestion/dataset.yaml"

data_validation:
  root_dir: "artifacts/data_validation"
  status_file_path: "artifacts/data_validation/status.txt"
  required_files: ["images", "labels", "dataset.yaml"]